<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>card_product</name>
   <tag></tag>
   <elementGuidId>8391da30-9d19-463d-915e-144e597b6382</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class= &quot;col-lg-4 col-md-6 mb-4&quot;][${no}]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>d6593ad5-46b9-48f4-b945-19c64ca14d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1727622927768</value>
      <webElementGuid>2211a580-56a4-4616-a182-1069555b607c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
